// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lqxjwbzmsathjsulcnth.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxxeGp3Ynptc2F0aGpzdWxjbnRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQxMzI4MDksImV4cCI6MjA4OTcwODgwOX0.eZXPwCc05Qj7lpmU2kup_jbdELtf90gvXUM82XuKyNw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});